name: Reclaim The Stack - Rubocop
description: Runs rubocop and posts offences as inline PR comments.
inputs:
  failure_exit_code:
    description: Exit code after running rubocop-- a non-zero exit code will fail the build
    default: "108"
  github_token:
    description: GITHUB_TOKEN
    default: ${{ github.token }}
  gem_versions:
    description: Gem versions to install
    default: rubocop:1.54.1 rubocop-rails:2.20.2 rubocop-rspec:2.22.0
  rubocop_arguments:
    description: Arguments passed to rubocop cli
    default: ""
runs:
  using: composite
  steps:
    - run: ruby $GITHUB_ACTION_PATH/rubocop.rb ${{ inputs.rubocop_arguments }}
      shell: bash
      env:
        FAILURE_EXIT_CODE: ${{ inputs.failure_exit_code }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        RUBOCOP_GEM_VERSIONS: ${{ inputs.gem_versions }}
